export const CATEGORIES = [
  {
    id: '1',
    name: 'Construction',
    icon: 'hammer',
    slug: 'construction',
    color: '#FF5722',
  },
  {
    id: '2',
    name: 'Electrical',
    icon: 'lightning-bolt',
    slug: 'electrical',
    color: '#FFC107',
  },
  {
    id: '3',
    name: 'Plumbing',
    icon: 'water-pump',
    slug: 'plumbing',
    color: '#2196F3',
  },
  {
    id: '4',
    name: 'Cleaning',
    icon: 'broom',
    slug: 'cleaning',
    color: '#00BCD4',
  },
  {
    id: '5',
    name: 'Gas & Heating',
    icon: 'fire',
    slug: 'gas',
    color: '#FF9800',
  },
  {
    id: '6',
    name: 'Carpentry',
    icon: 'saw-blade',
    slug: 'carpentry',
    color: '#8D6E63',
  },
  {
    id: '7',
    name: 'Mechanical',
    icon: 'wrench',
    slug: 'mechanical',
    color: '#607D8B',
  },
  {
    id: '8',
    name: 'Maintenance',
    icon: 'toolbox',
    slug: 'maintenance',
    color: '#4CAF50',
  },
  {
    id: '9',
    name: 'Transport',
    icon: 'truck-delivery',
    slug: 'transport',
    color: '#9C27B0',
  },
  {
    id: '10',
    name: 'Finishing',
    icon: 'format-paint',
    slug: 'finishing',
    color: '#E91E63',
  },
  {
    id: '11',
    name: 'Tech Services',
    icon: 'laptop',
    slug: 'tech',
    color: '#3F51B5',
  },
  {
    id: '12',
    name: 'Agriculture',
    icon: 'sprout',
    slug: 'agriculture',
    color: '#8BC34A',
  },
  {
    id: '13',
    name: 'Safety',
    icon: 'shield-check',
    slug: 'safety',
    color: '#F44336',
  },
];
