export const CATEGORIES = [
  {
    id: '1',
    name: 'Construction',
    icon: 'hammer',
    slug: 'construction',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '2',
    name: 'Electrical',
    icon: 'lightning-bolt',
    slug: 'electrical',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '3',
    name: 'Plumbing',
    icon: 'water-pump',
    slug: 'plumbing',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '4',
    name: 'IT / Tech',
    icon: 'laptop',
    slug: 'it-tech',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '5',
    name: 'Cleaning',
    icon: 'broom',
    slug: 'cleaning',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '6',
    name: 'Beauty',
    icon: 'face-woman',
    slug: 'beauty',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '7',
    name: 'Transport',
    icon: 'truck-delivery',
    slug: 'transport',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '8',
    name: 'Education',
    icon: 'school',
    slug: 'education',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '9',
    name: 'Healthcare',
    icon: 'heart-pulse',
    slug: 'healthcare',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
  {
    id: '10',
    name: 'Repair',
    icon: 'wrench',
    slug: 'repair',
    lottie: require('@/assets/lottie/gradientBall.json'),
  },
];
