export const PROBLEMS = [
  {
    id: 'p1',
    name: 'Walls cracking / uneven floors',
    category: 'construction',
    icon: 'wall',
    slug: 'wall-cracks',
    color: '#FF5722',
  },
  {
    id: 'p2',
    name: 'Roof leaks / weak foundations',
    category: 'construction',
    icon: 'home-roof',
    slug: 'roof-leak',
    color: '#795548',
  },
  {
    id: 'p3',
    name: 'Power points not working',
    category: 'electrical',
    icon: 'power-socket-uk',
    slug: 'power-fault',
    color: '#FFC107',
  },
  {
    id: 'p4',
    name: 'Faulty wiring / short circuits',
    category: 'electrical',
    icon: 'flash-alert',
    slug: 'wiring-issue',
    color: '#F44336',
  },
  {
    id: 'p5',
    name: 'Blocked toilets / sinks',
    category: 'plumbing',
    icon: 'water-off',
    slug: 'blocked-drain',
    color: '#2196F3',
  },
  {
    id: 'p6',
    name: 'Leaking taps & pipes',
    category: 'plumbing',
    icon: 'pipe-leak',
    slug: 'leakage',
    color: '#03A9F4',
  },
  {
    id: 'p7',
    name: 'Gas leaks / stove problems',
    category: 'gas',
    icon: 'gas-cylinder',
    slug: 'gas-issue',
    color: '#FF9800',
  },
  {
    id: 'p8',
    name: 'Broken doors / windows',
    category: 'carpentry',
    icon: 'door-open',
    slug: 'broken-door',
    color: '#8D6E63',
  },
  {
    id: 'p9',
    name: 'Broken locks / keys',
    category: 'maintenance',
    icon: 'lock-open-variant',
    slug: 'lock-repair',
    color: '#607D8B',
  },
  {
    id: 'p10',
    name: 'Houses deep cleaning',
    category: 'cleaning',
    icon: 'broom',
    slug: 'deep-cleaning',
    color: '#00BCD4',
  },
  {
    id: 'p11',
    name: 'Internet / WiFi issues',
    category: 'tech',
    icon: 'wifi-strength-1',
    slug: 'internet-fault',
    color: '#3F51B5',
  },
  {
    id: 'p12',
    name: 'CCTV / Security malfunction',
    category: 'tech',
    icon: 'cctv',
    slug: 'security-fault',
    color: '#333333',
  },
];

export type Problem = (typeof PROBLEMS)[0];
