export const WORKER_TYPES = [
  // 1. Home Repair & Maintenance
  { id: "w1", name: "Painter", icon: "format-paint", color: "#E91E63" },
  { id: "w2", name: "Plumber", icon: "pipe-wrench", color: "#2196F3" },
  { id: "w3", name: "Electrician", icon: "flash", color: "#FFC107" },
  { id: "w4", name: "Carpenter", icon: "hammer-wrench", color: "#8D6E63" },
  { id: "w5", name: "Handyman", icon: "tools", color: "#4CAF50" },
  { id: "w6", name: "Mason", icon: "wall", color: "#FF5722" },
  { id: "w7", name: "Welder", icon: "fountain-pen-tip", color: "#607D8B" },
  { id: "w8", name: "House cleaning", icon: "broom", color: "#00BCD4" },
  { id: "w9", name: "Maid / house helper", icon: "account-child", color: "#009688" },
  { id: "w10", name: "Deep cleaning", icon: "vacuum", color: "#00ACC1" },
  { id: "w11", name: "Office cleaning", icon: "office-building", color: "#546E7A" },
  { id: "w12", name: "Ironing / laundry", icon: "iron", color: "#9C27B0" },
  { id: "w13", name: "Gardening helper", icon: "flower", color: "#43A047" },
  { id: "w14", name: "Lorry hire", icon: "truck", color: "#F44336" },
  { id: "w15", name: "Van hire", icon: "van-utility", color: "#FF9800" },
  { id: "w16", name: "Furniture movers", icon: "sofa", color: "#795548" },
  { id: "w17", name: "Goods transport", icon: "package-variant-closed", color: "#FF5252" },
  { id: "w18", name: "Courier riders", icon: "motorbike", color: "#FB8C00" },
  { id: "w19", name: "Loading/unloading helpers", icon: "human-handsup", color: "#8D6E63" },
  { id: "w20", name: "Washing machine repair", icon: "washing-machine", color: "#2196F3" },
  { id: "w21", name: "Refrigerator repair", icon: "fridge", color: "#03A9F4" },
  { id: "w22", name: "AC repair/service", icon: "air-conditioner", color: "#00BCD4" },
  { id: "w23", name: "Water heater repair", icon: "water-boiler", color: "#FF5722" },
  { id: "w24", name: "Cooker repair", icon: "stove", color: "#FF9800" },
  { id: "w25", name: "TV repair", icon: "television", color: "#3F51B5" },
  { id: "w26", name: "Computer repair", icon: "laptop", color: "#3F51B5" },
  { id: "w27", name: "Laptop repair", icon: "laptop-mac", color: "#673AB7" },
  { id: "w28", name: "Mobile phone repair", icon: "cellphone", color: "#9C27B0" },
  { id: "w29", name: "Network setup", icon: "router-wireless", color: "#2196F3" },
  { id: "w30", name: "CCTV installation", icon: "cctv", color: "#455A64" },
  { id: "w31", name: "Printer repair", icon: "printer", color: "#757575" },
  { id: "w32", name: "IT support", icon: "help-circle", color: "#1A237E" },
  { id: "w33", name: "Graphic designer", icon: "palette", color: "#E91E63" },
  { id: "w34", name: "Web developer", icon: "code-tags", color: "#2196F3" },
  { id: "w35", name: "Video editor", icon: "video", color: "#F44336" },
  { id: "w36", name: "Social media manager", icon: "share-variant", color: "#3F51B5" },
  { id: "w37", name: "Data entry operator", icon: "keyboard", color: "#607D8B" },
  { id: "w38", name: "Barber", icon: "content-cut", color: "#795548" },
  { id: "w39", name: "Hairdresser", icon: "face-woman", color: "#E91E63" },
  { id: "w40", name: "Makeup artist", icon: "brush", color: "#FF4081" },
  { id: "w41", name: "Bridal dressing", icon: "ring", color: "#D81B60" },
  { id: "w42", name: "Mehendi artist", icon: "hands-pray", color: "#81C784" },
  { id: "w43", name: "Nail technician", icon: "hand-pointing-right", color: "#F06292" },
  { id: "w44", name: "Home nurse", icon: "hospital-marker", color: "#F44336" },
  { id: "w45", name: "Caregiver", icon: "heart", color: "#E91E63" },
  { id: "w46", name: "Physiotherapist", icon: "human-handsdown", color: "#4CAF50" },
  { id: "w47", name: "Massage therapist", icon: "human-handsup", color: "#8D6E63" },
  { id: "w48", name: "Fitness trainer", icon: "dumbbell", color: "#212121" },
  { id: "w49", name: "Diet consultant", icon: "food-apple", color: "#4CAF50" },
  { id: "w50", name: "School tutors", icon: "book-open-variant", color: "#3F51B5" },
  { id: "w51", name: "Language teachers", icon: "translate", color: "#FFC107" },
  { id: "w52", name: "Online tutors", icon: "video-account", color: "#2196F3" },
  { id: "w53", name: "Quran/religious teachers", icon: "book", color: "#4CAF50" },
  { id: "w54", name: "Music teachers", icon: "music", color: "#9C27B0" },
  { id: "w55", name: "Photographer", icon: "camera", color: "#3F51B5" },
  { id: "w56", name: "Videographer", icon: "video-camera", color: "#F44336" },
  { id: "w57", name: "DJ", icon: "disc-player", color: "#000000" },
  { id: "w58", name: "Sound system rental", icon: "speaker", color: "#424242" },
  { id: "w59", name: "Event decorators", icon: "party-popper", color: "#FF4081" },
  { id: "w60", name: "Wedding planners", icon: "account-group", color: "#9C27B0" },
  { id: "w61", name: "Car mechanic", icon: "car-wrench", color: "#607D8B" },
  { id: "w62", name: "Bike mechanic", icon: "motorbike", color: "#FF5722" },
  { id: "w63", name: "Mobile mechanic (home visit)", icon: "map-marker-radius", color: "#4CAF50" },
  { id: "w64", name: "Car electrician", icon: "car-electric", color: "#FFC107" },
  { id: "w65", name: "Car wash service", icon: "car-wash", color: "#03A9F4" },
  { id: "w66", name: "Contractors", icon: "briefcase-account", color: "#5D4037" },
  { id: "w67", name: "House builders", icon: "home-city", color: "#795548" },
  { id: "w68", name: "Interior designers", icon: "couch", color: "#9C27B0" },
  { id: "w69", name: "Ceiling workers", icon: "ceiling-light", color: "#607D8B" },
  { id: "w70", name: "Kitchen cupboard makers", icon: "cupboard", color: "#8D6E63" },
  { id: "w71", name: "Security guards", icon: "security", color: "#263238" },
  { id: "w72", name: "Locksmith / key maker", icon: "key", color: "#607D8B" },
  { id: "w73", name: "Alarm installation", icon: "alarm-bell", color: "#F44336" },
  { id: "w74", name: "CCTV monitoring", icon: "monitor-eye", color: "#455A64" },
  { id: "w75", name: "Pet grooming", icon: "dog-side", color: "#FFB300" },
  { id: "w76", name: "Dog walking", icon: "dog-service", color: "#FF9800" },
  { id: "w77", name: "Pet boarding", icon: "home-heart", color: "#E91E63" },
  { id: "w78", name: "Vet home visit", icon: "medical-bag", color: "#F44336" },
  { id: "w79", name: "Aquarium cleaning", icon: "fish", color: "#03A9F4" },
  { id: "w80", name: "Landscaping", icon: "sprout", color: "#4CAF50" },
  { id: "w81", name: "Tree cutting", icon: "pine-tree", color: "#388E3C" },
  { id: "w82", name: "Lawn mowing", icon: "mower", color: "#454545" },
  { id: "w83", name: "Garden design", icon: "flower-outline", color: "#8BC34A" },
  { id: "w84", name: "Pest control (outdoor)", icon: "bug", color: "#D32F2F" },
  { id: "w85", name: "Office assistants", icon: "account-tie", color: "#546E7A" },
  { id: "w86", name: "Accountants", icon: "calculator", color: "#455A64" },
  { id: "w87", name: "Bookkeeping", icon: "book-plus", color: "#607D8B" },
  { id: "w88", name: "Typing services", icon: "typewriter", color: "#757575" },
  { id: "w89", name: "Printing services", icon: "printer-pos", color: "#424242" },
  { id: "w90", name: "Home cooks", icon: "chef-hat", color: "#FFAB91" },
  { id: "w91", name: "Catering service", icon: "food-variant", color: "#FF5722" },
  { id: "w92", name: "Cake makers", icon: "cake-variant", color: "#E91E63" },
  { id: "w93", name: "Tiffin/meal providers", icon: "food-box", color: "#FBC02D" },
  { id: "w94", name: "BBQ service", icon: "grill", color: "#D32F2F" },
  { id: "w95", name: "Tailors", icon: "needle", color: "#795548" },
  { id: "w96", name: "Dressmakers", icon: "hanger", color: "#9C27B0" },
  { id: "w97", name: "Alteration services", icon: "scissors-cutting", color: "#607D8B" },
  { id: "w98", name: "Embroidery", icon: "palette-swatch", color: "#E91E63" },
  { id: "w99", name: "Bridal wear stitching", icon: "human-female-girl", color: "#D81B60" },
  { id: "w100", name: "Emergency electrician", icon: "flash-alert", color: "#FFC107" },
  { id: "w101", name: "Emergency plumber", icon: "alert-decagram", color: "#2196F3" },
  { id: "w102", name: "Towing service", icon: "tow-truck", color: "#F44336" },
  { id: "w103", name: "Battery jumpstart", icon: "battery-status-60", color: "#4CAF50" },
  { id: "w104", name: "Lockout service", icon: "key-alert", color: "#607D8B" },
];

export type WorkerType = (typeof WORKER_TYPES)[0];
